<a href="https://colab.research.google.com/github/Alenushka2013/Khpi_master_studing/blob/main/IDT_Lab_1_Vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from typing import Sequence

import numpy as np
from scipy import sparse


def get_vector(dim: int) -> np.ndarray:
    """Create random column vector with dimension dim.

    Args:
        dim (int): vector dimension.

    Returns:
        np.ndarray: column vector.
    """
    return np.random.rand(dim, 1)

In [5]:
get_vector(3)

array([[0.87691007],
       [0.59245884],
       [0.1749049 ]])

In [79]:
def get_sparse_vector(dim: int, density: float = 0.5) -> sparse.coo_matrix:
    """Create random sparse column vector with dimension dim.

    Args:
        dim (int): vector dimension.

    Returns:
        sparse.coo_matrix: sparse column vector.
    """
    data = np.random.rand(dim)
    mask = np.random.rand(dim) < density
    data[mask] = 0
    row = np.arange(dim)
    col = np.zeros(dim)
    return sparse.coo_matrix((data, (row, col)), shape=(dim, 1))

In [84]:
get_sparse_vector(20).toarray()

array([[0.        ],
       [0.        ],
       [0.75782335],
       [0.        ],
       [0.71432153],
       [0.        ],
       [0.7556875 ],
       [0.94627835],
       [0.04073842],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.03794454],
       [0.        ],
       [0.49381247],
       [0.        ],
       [0.56515622],
       [0.        ],
       [0.11769409],
       [0.93421617]])

In [83]:
def add(x: np.ndarray, y: np.ndarray) -> np.ndarray:
    """Vector addition.

    Args:
        x (np.ndarray): 1th vector.
        y (np.ndarray): 2nd vector.

    Returns:
        np.ndarray: vector sum.
    """
    return x + y


In [12]:
add(np.array([1, 2, 3]), np.array([5, 6, 7]))

array([ 6,  8, 10])

In [13]:
def scalar_multiplication(x: np.ndarray, a: float) -> np.ndarray:
    """Vector multiplication by scalar.

    Args:
        x (np.ndarray): vector.
        a (float): scalar.

    Returns:
        np.ndarray: multiplied vector.
    """
    return a * x

In [15]:
#scalar_multiplication(np.ndarray([1, 2, 3]), 5)
scalar_multiplication(np.array([1,2,3]), 2)

array([2, 4, 6])

In [16]:
scalar_multiplication(np.ndarray([1, 2, 3]), 5)

array([[[7.86740819e-314, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]]])

In [19]:
def linear_combination(vectors: Sequence[np.ndarray], coeffs: Sequence[float]) -> np.ndarray:##
    """Linear combination of vectors.

    Args:
        vectors (Sequence[np.ndarray]): list of vectors of len N.
        coeffs (Sequence[float]): list of coefficients of len N.

    Returns:
        np.ndarray: linear combination of vectors.
    """
    if len(vectors) != len(coeffs):
      raise ValueError("The number of vectors does not match the number of coefficients.")

    result = np.zeros_like(vectors[0])
    for v, c in zip(vectors, coeffs):
        result += c * v
    return result


In [20]:
linear_combination([np.array([1,0]), np.array([0,1])], [2,3])

array([2, 3])

In [89]:
def dot_product(x: np.ndarray, y: np.ndarray) -> float:
    """Vectors dot product.

    Args:
        x (np.ndarray): 1th vector.
        y (np.ndarray): 2nd vector.

    Returns:
        float: dot product.
    """
    return float(np.dot(x, y))

In [92]:
dot_product(np.array([1,2,3]), np.array([4,5,6]))

32.0

In [98]:
def norm(x: np.ndarray, order: int | float) -> float:
    """Vector norm: Manhattan, Euclidean or Max.

    Args:
        x (np.ndarray): vector
        order (int | float): norm's order: 1, 2 or inf.

    Returns:
        float: vector norm
    """
    #x = np.ravel(x)

    if order == 1:
        #  Manhattan: |x1| + |x2| + ... + |xn|
        return float(np.sum(np.abs(x)))

    elif order == 2:
        # Euclidean: sqrt(x1² + x2² + ... + xn²)
        return float(np.sqrt(np.sum(x ** 2)))

    elif order == np.inf:
        # Max: max(|x1|, |x2|, ..., |xn|)
        return float(np.max(np.abs(x)))

    else:
        raise ValueError("Only norms of order 1, 2, or np.inf are supported")

In [101]:
norm(np.array([3,4]), 1)

7.0

In [41]:
def distance(x: np.ndarray, y: np.ndarray) -> float: ##
    """L2 distance between vectors.

    Args:
        x (np.ndarray): 1th vector.
        y (np.ndarray): 2nd vector.

    Returns:
        float: distance.
    """
    return float(sum((x-y) ** 2)) ** 0.5


In [42]:
distance(np.array([1,2]), np.array([4,6]))

5.0

In [45]:
def cos_between_vectors(x: np.ndarray, y: np.ndarray) -> float:
    """Cosine between vectors in deg.

    Args:
        x (np.ndarray): 1th vector.
        y (np.ndarray): 2nd vector.


    Returns:
        np.ndarray: angle in deg.
    """
    cos_theta = dot_product(x, y) / (norm(x, 2) * norm(y, 2))
    angle_rad = np.arccos(cos_theta)
    return float(np.degrees(angle_rad))

In [46]:
cos_between_vectors(np.array([1,1]), np.array([0,1]))

45.00000000000001

In [102]:
def is_orthogonal(x: np.ndarray, y: np.ndarray) -> bool:
    """Check is vectors orthogonal.

    Args:
        x (np.ndarray): 1th vector.
        y (np.ndarray): 2nd vector.


    Returns:
        bool: are vectors orthogonal.
    """
    return float(np.dot(x, y)) == 0

In [103]:
is_orthogonal(np.array([5,2]), np.array([2,-5]))

True

In [56]:
def solves_linear_systems(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    """Solve system of linear equations.

    Args:
        a (np.ndarray): coefficient matrix.
        b (np.ndarray): ordinate values.

    Returns:
        np.ndarray: sytems solution
    """
    if a.shape[0] != a.shape[1]:
        raise ValueError("Matrix 'a' must be square")

    if a.shape[0] != b.shape[0]:
        raise ValueError("Matrix 'a' and vector 'b' dimensions do not match")

    det = np.linalg.det(a)
    if np.isclose(det, 0.0):
        raise ValueError("Matrix 'a' is singular — the system has no unique solution")

    a_inv = np.linalg.inv(a)
    x = a_inv.dot(b)

    return x

In [61]:
A = np.array([[2, 1], [2, 3]])
b = np.array([10, 15])
x = solves_linear_systems(A, b)
print(x)

[3.75 2.5 ]


In [104]:
from typing import Sequence

import numpy as np
from scipy import sparse


def get_vector(dim: int) -> np.ndarray:
    """Create random column vector with dimension dim.

    Args:
        dim (int): vector dimension.

    Returns:
        np.ndarray: column vector.
    """
    return np.random.rand(dim, 1)


def get_sparse_vector(dim: int, density: float = 0.5) -> sparse.coo_matrix:
    """Create random sparse column vector with dimension dim.

    Args:
        dim (int): vector dimension.

    Returns:
        sparse.coo_matrix: sparse column vector.
    """
    data = np.random.rand(dim)
    mask = np.random.rand(dim) < density
    data[mask] = 0

    row = np.arange(dim)
    col = np.zeros(dim)

    return sparse.coo_matrix((data, (row, col)), shape=(dim, 1))


def add(x: np.ndarray, y: np.ndarray) -> np.ndarray:
    """Vector addition.

    Args:
        x (np.ndarray): 1th vector.
        y (np.ndarray): 2nd vector.

    Returns:
        np.ndarray: vector sum.
    """
    return x + y


def scalar_multiplication(x: np.ndarray, a: float) -> np.ndarray:
    """Vector multiplication by scalar.

    Args:
        x (np.ndarray): vector.
        a (float): scalar.

    Returns:
        np.ndarray: multiplied vector.
    """
    return a * x


def linear_combination(vectors: Sequence[np.ndarray], coeffs: Sequence[float]) -> np.ndarray:
    """Linear combination of vectors.

    Args:
        vectors (Sequence[np.ndarray]): list of vectors of len N.
        coeffs (Sequence[float]): list of coefficients of len N.

    Returns:
        np.ndarray: linear combination of vectors.
    """
    if len(vectors) != len(coeffs):
      raise ValueError("The number of vectors does not match the number of coefficients.")

    result = np.zeros_like(vectors[0])
    for v, c in zip(vectors, coeffs):
        result += c * v

    return result


def dot_product(x: np.ndarray, y: np.ndarray) -> float:
    """Vectors dot product.

    Args:
        x (np.ndarray): 1th vector.
        y (np.ndarray): 2nd vector.

    Returns:
        float: dot product.
    """
    return float(np.dot(x, y))


def norm(x: np.ndarray, order: int | float) -> float:
    """Vector norm: Manhattan, Euclidean or Max.

    Args:
        x (np.ndarray): vector
        order (int | float): norm's order: 1, 2 or inf.

    Returns:
        float: vector norm
    """
    if order == 1:
        #  Manhattan: |x1| + |x2| + ... + |xn|
        return float(np.sum(np.abs(x)))

    elif order == 2:
        # Euclidean: sqrt(x1² + x2² + ... + xn²)
        return float(np.sqrt(np.sum(x ** 2)))

    elif order == np.inf:
        # Max: max(|x1|, |x2|, ..., |xn|)
        return float(np.max(np.abs(x)))

    else:
        raise ValueError("Only norms of order 1, 2, or np.inf are supported")


def distance(x: np.ndarray, y: np.ndarray) -> float:
    """L2 distance between vectors.

    Args:
        x (np.ndarray): 1th vector.
        y (np.ndarray): 2nd vector.

    Returns:
        float: distance.
    """
    return float(sum((x-y) ** 2)) ** 0.5


def cos_between_vectors(x: np.ndarray, y: np.ndarray) -> float:
    """Cosine between vectors in deg.

    Args:
        x (np.ndarray): 1th vector.
        y (np.ndarray): 2nd vector.


    Returns:
        np.ndarray: angle in deg.
    """

    cos_theta = dot_product(x, y) / (norm(x, 2) * norm(y, 2))
    angle_rad = np.arccos(cos_theta)

    return float(np.degrees(angle_rad))

def is_orthogonal(x: np.ndarray, y: np.ndarray) -> bool:
    """Check is vectors orthogonal.

    Args:
        x (np.ndarray): 1th vector.
        y (np.ndarray): 2nd vector.


    Returns:
        bool: are vectors orthogonal.
    """
    return float(np.dot(x, y)) == 0


def solves_linear_systems(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    """Solve system of linear equations.

    Args:
        a (np.ndarray): coefficient matrix.
        b (np.ndarray): ordinate values.

    Returns:
        np.ndarray: sytems solution
    """
    if a.shape[0] != a.shape[1]:
        raise ValueError("Matrix 'a' must be square")

    if a.shape[0] != b.shape[0]:
        raise ValueError("Matrix 'a' and vector 'b' dimensions do not match")

    det = np.linalg.det(a)
    if np.isclose(det, 0.0):
        raise ValueError("Matrix 'a' is singular — the system has no unique solution")

    a_inv = np.linalg.inv(a)
    x = a_inv.dot(b)

    return x

In [105]:
import numpy as np
from scipy import sparse

# Припустимо, ти вже виконав комірку з усіма реалізованими функціями (get_vector тощо)
# Тоді просто запускаєш цей блок:

# === 1. Перевірка генерації векторів ===
v = get_vector(5)
assert v.shape == (5, 1), "get_vector має повертати вектор-стовпець"
assert (v >= 0).all() and (v <= 1).all(), "елементи мають бути у [0,1]"

sv = get_sparse_vector(5)
assert sparse.issparse(sv), "get_sparse_vector має повертати sparse матрицю"
assert sv.shape == (5, 1), "sparse вектор має бути стовпцем"

# === 2. Перевірка базових операцій ===
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
assert np.allclose(add(x, y), np.array([5, 7, 9]))
assert np.allclose(scalar_multiplication(x, 2), np.array([2, 4, 6]))

# === 3. Лінійна комбінація ===
v1 = np.array([1, 0])
v2 = np.array([0, 1])
res = linear_combination([v1, v2], [2, 3])
assert np.allclose(res, np.array([2, 3]))

# === 4. Скалярний добуток і норми ===
assert np.isclose(dot_product(x, y), 32)
assert np.isclose(norm(np.array([3, 4]), 2), 5)
assert np.isclose(norm(np.array([1, 2, 3]), 1), 6)
assert np.isclose(norm(np.array([-1, 3, -2]), np.inf), 3)

# === 5. Відстань ===
assert np.isclose(distance(np.array([1, 2]), np.array([4, 6])), 5)

# === 6. Кут між векторами ===
angle = cos_between_vectors(np.array([1, 0]), np.array([0, 1]))
assert np.isclose(angle, 90.0)

angle2 = cos_between_vectors(np.array([1, 0]), np.array([1, 1]))
assert np.isclose(angle2, 45.0)

# === 7. Перевірка ортогональності ===
assert is_orthogonal(np.array([1, 0]), np.array([0, 1]))
assert not is_orthogonal(np.array([1, 1]), np.array([1, 0]))

# === 8. Розв’язання системи лінійних рівнянь ===
A = np.array([[2, 1], [1, 3]])
b = np.array([10, 15])
sol = solves_linear_systems(A, b)
assert np.allclose(sol, np.array([3, 4]))

print("✅ Усі перевірки пройдено успішно!")

✅ Усі перевірки пройдено успішно!


In [106]:
def run_tests():
    print("Тест 1: get_vector ✅")
    get_vector(3)

    print("Тест 2: add, scalar_multiplication ✅")
    assert np.allclose(add(np.array([1,2]), np.array([3,4])), np.array([4,6]))

    print("Тест 3: solves_linear_systems ✅")
    A = np.array([[1,2],[3,4]])
    b = np.array([5,11])
    x = solves_linear_systems(A, b)
    print("Розв’язок:", x)

    print("✅ Усі функції працюють коректно!")

run_tests()

Тест 1: get_vector ✅
Тест 2: add, scalar_multiplication ✅
Тест 3: solves_linear_systems ✅
Розв’язок: [1. 2.]
✅ Усі функції працюють коректно!
