<a href="https://colab.research.google.com/github/Alenushka2013/Khpi_master_studing/blob/main/IDT_Lab_2_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [112]:
import numpy as np


def get_matrix(n: int, m: int) -> np.ndarray:
    """Create random matrix n * m.

    Args:
        n (int): number of rows.
        m (int): number of columns.

    Returns:
        np.ndarray: matrix n*m.
    """
    return np.random.rand(n, m)


In [113]:
get_matrix(3, 4)

array([[0.31052655, 0.83635425, 0.05015636, 0.87854626],
       [0.01063762, 0.08735588, 0.33936788, 0.22504146],
       [0.75506906, 0.49790008, 0.83804092, 0.57962588]])

In [114]:
def add(x: np.ndarray, y: np.ndarray) -> np.ndarray:
    """Matrix addition.

    Args:
        x (np.ndarray): 1st matrix.
        y (np.ndarray): 2nd matrix.

    Returns:
        np.ndarray: matrix sum.
    """
    return x + y

In [123]:
a = np.array([[1, 2, 3], [5, 6, 7], [1, 1, 1]])
b = np.array([[4, 3, 2], [7, 6, 5], [3, 2, 1]])
add(a, b)

array([[ 5,  5,  5],
       [12, 12, 12],
       [ 4,  3,  2]])

In [119]:
def scalar_multiplication(x: np.ndarray, a: float) -> np.ndarray:
    """Matrix multiplication by scalar.

    Args:
        x (np.ndarray): matrix.
        a (float): scalar.

    Returns:
        np.ndarray: multiplied matrix.
    """
    return a * x

In [120]:
scalar_multiplication(a, 2.5)

array([[ 2.5,  5. ,  7.5],
       [12.5, 15. , 17.5]])

In [125]:
def dot_product(x: np.ndarray, y: np.ndarray) -> np.ndarray:
    """Matrices dot product.

    Args:
        x (np.ndarray): 1st matrix.
        y (np.ndarray): 2nd matrix or vector.

    Returns:
        np.ndarray: dot product.
    """
    return x @ y

In [126]:
dot_product(a, b)

array([[27, 21, 15],
       [83, 65, 47],
       [14, 11,  8]])

In [127]:
def identity_matrix(dim: int) -> np.ndarray:
    """Create identity matrix with dimension `dim`.

    Args:
        dim (int): matrix dimension.

    Returns:
        np.ndarray: identity matrix.
    """
    return np.eye(dim)

In [137]:
def matrix_inverse(x: np.ndarray) -> np.ndarray:
    """Compute inverse matrix.

    Args:
        x (np.ndarray): matrix.

    Returns:
        np.ndarray: inverse matrix.
    """
    return np.linalg.inv(x)

In [128]:
def matrix_transpose(x: np.ndarray) -> np.ndarray:
    """Compute transpose matrix.

    Args:
        x (np.ndarray): matrix.

    Returns:
        np.ndarray: transosed matrix.
    """
    return x.T

In [130]:
matrix_transpose(np.array([[1, 2, 3], [3, 2, 1]]))

array([[1, 3],
       [2, 2],
       [3, 1]])

In [131]:
def hadamard_product(x: np.ndarray, y: np.ndarray) -> np.ndarray:
    """Compute hadamard product.

    Args:
        x (np.ndarray): 1th matrix.
        y (np.ndarray): 2nd matrix.

    Returns:
        np.ndarray: hadamard produc
    """
    return x * y

In [132]:
hadamard_product(a, b)

array([[ 4,  6,  6],
       [35, 36, 35],
       [ 3,  2,  1]])

In [133]:
def basis(x: np.ndarray) -> tuple[int]:
    """Compute matrix basis.

    Args:
        x (np.ndarray): matrix.

    Returns:
        tuple[int]: indexes of basis columns.
    """
    Q, R = np.linalg.qr(x)

    return tuple(i for i, r in enumerate(np.abs(np.diag(R)) > 1e-10))

In [155]:
basis(np.array([[1, 2, 3], [4, 5, 6], [5, 7, 9], [3, 3, 3]]).T)

(0, 1)

In [135]:
# def norm(x: np.ndarray, order: int | float | str) -> float:
#     """Matrix norm: Frobenius, Spectral or Max.

#     Args:
#         x (np.ndarray): vector
#         order (int | float): norm's order: 'fro', 2 or inf.

#     Returns:
#         float: vector norm
#     """
#     if order == 'fro':
#       return np.sqrt(np.sum(x**2))
#     elif order == 2:
#         return np.linalg.svd(x, compute_uv=False)[0]
#     elif order == np.inf:
#         return np.max(np.sum(np.abs(x), axis=1))
#     else:
#         return np.sum(np.abs(x)**order)**(1/order)

In [ ]:
def norm(x: np.ndarray, order: int | float | str) -> float:
    """Matrix or vector norm."""
    if order == 'fro':
        return np.linalg.norm(x, 'fro') #np.sqrt(np.sum(x**2))
    elif order == 2:
        # Спектральна норма: sqrt(max eigenvalue of A^T A)
        eigvals = np.linalg.eigvals(x.T @ x)
        return np.sqrt(np.max(np.real(eigvals)))  # беремо дійсну частину на всяк випадок
    elif order == np.inf:
        return np.linalg.norm(x, np.inf) #np.max(np.sum(np.abs(x), axis=1))
    else:
        # Узагальнений p-норма для векторів
        return np.sum(np.abs(x)**order)**(1/order)

In [165]:
def norm(x: np.ndarray, order: int | float | str) -> float:
    """Matrix or vector norm."""

    return float(np.linalg.norm(x, order))

In [164]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
norm(A, 2)

np.float64(16.84810335261421)

In [166]:
norm(A, 'fro')

16.881943016134134

In [167]:
norm(A, np.inf)

24.0

In [168]:
import numpy as np


def get_matrix(n: int, m: int) -> np.ndarray:
    """Create random matrix n * m.

    Args:
        n (int): number of rows.
        m (int): number of columns.

    Returns:
        np.ndarray: matrix n*m.
    """
    return np.random.rand(n, m)


def add(x: np.ndarray, y: np.ndarray) -> np.ndarray:
    """Matrix addition.

    Args:
        x (np.ndarray): 1st matrix.
        y (np.ndarray): 2nd matrix.

    Returns:
        np.ndarray: matrix sum.
    """
    return x + y


def scalar_multiplication(x: np.ndarray, a: float) -> np.ndarray:
    """Matrix multiplication by scalar.

    Args:
        x (np.ndarray): matrix.
        a (float): scalar.

    Returns:
        np.ndarray: multiplied matrix.
    """
    return a * x


def dot_product(x: np.ndarray, y: np.ndarray) -> np.ndarray:
    """Matrices dot product.

    Args:
        x (np.ndarray): 1st matrix.
        y (np.ndarray): 2nd matrix or vector.

    Returns:
        np.ndarray: dot product.
    """
    return x @ y


def identity_matrix(dim: int) -> np.ndarray:
    """Create identity matrix with dimension `dim`.

    Args:
        dim (int): matrix dimension.

    Returns:
        np.ndarray: identity matrix.
    """
    return np.eye(dim)


def matrix_inverse(x: np.ndarray) -> np.ndarray:
    """Compute inverse matrix.

    Args:
        x (np.ndarray): matrix.

    Returns:
        np.ndarray: inverse matrix.
    """
    return np.linalg.inv(x)


def matrix_transpose(x: np.ndarray) -> np.ndarray:
    """Compute transpose matrix.

    Args:
        x (np.ndarray): matrix.

    Returns:
        np.ndarray: transosed matrix.
    """
    return x.T


def hadamard_product(x: np.ndarray, y: np.ndarray) -> np.ndarray:
    """Compute hadamard product.

    Args:
        x (np.ndarray): 1th matrix.
        y (np.ndarray): 2nd matrix.

    Returns:
        np.ndarray: hadamard produc
    """
    return x * y


def basis(x: np.ndarray) -> tuple[int]:
    """Compute matrix basis.

    Args:
        x (np.ndarray): matrix.

    Returns:
        tuple[int]: indexes of basis columns.
    """
    Q, R = np.linalg.qr(x)

    return tuple(i for i, r in enumerate(np.abs(np.diag(R)) > 1e-10))


def norm(x: np.ndarray, order: int | float | str) -> float:
    """Matrix norm: Frobenius, Spectral or Max.

    Args:
        x (np.ndarray): vector
        order (int | float): norm's order: 'fro', 2 or inf.

    Returns:
        float: vector norm
    """
    return float(np.linalg.norm(x, order))


In [169]:
import numpy as np

# --- Тестові дані ---
A = get_matrix(3, 3)
B = get_matrix(3, 3)
v = get_matrix(3, 1)
scalar = 2.5

print("Матриця A:\n", A)
print("Матриця B:\n", B)
print("Вектор v:\n", v)
print("Скаляр:", scalar)

# --- Додавання ---
C = add(A, B)
print("\nA + B =\n", C)

# --- Множення на скаляр ---
D = scalar_multiplication(A, scalar)
print("\nA * scalar =\n", D)

# --- Добуток матриць ---
E = dot_product(A, B)
print("\nA @ B =\n", E)

# --- Транспонування ---
At = matrix_transpose(A)
print("\nA^T =\n", At)

# --- Ідентична матриця ---
I = identity_matrix(3)
print("\nIdentity matrix:\n", I)

# --- Інверсія (якщо матриця невироджена) ---
try:
    A_inv = matrix_inverse(A)
    print("\nInverse of A:\n", A_inv)
    # Перевірка: A @ A_inv ≈ I
    print("\nA @ A_inv ≈ I:\n", dot_product(A, A_inv))
except np.linalg.LinAlgError:
    print("\nМатриця A невироджена, інверсія неможлива.")

# --- Hadamard product ---
H = hadamard_product(A, B)
print("\nHadamard product A * B:\n", H)

# --- Базис ---
basis_indices = basis(A)
print("\nІндекси базисних стовпців A:", basis_indices)

# --- Норми ---
print("\nFrobenius norm of A:", norm(A, 'fro'))
print("Spectral norm of A:", norm(A, 2))
print("Infinity norm of A:", norm(A, np.inf))
print("2-norm of vector v:", norm(v, 2))


Матриця A:
 [[0.4937956  0.52273283 0.42754102]
 [0.02541913 0.10789143 0.03142919]
 [0.63641041 0.31435598 0.50857069]]
Матриця B:
 [[0.90756647 0.24929223 0.41038292]
 [0.75555114 0.22879817 0.07697991]
 [0.28975145 0.16122129 0.92969765]]
Вектор v:
 [[0.80812038]
 [0.63340376]
 [0.87146059]]
Скаляр: 2.5

A + B =
 [[1.40136207 0.77202506 0.83792394]
 [0.78097027 0.33668959 0.1084091 ]
 [0.92616186 0.47557727 1.43826834]]

A * scalar =
 [[1.23448899 1.30683207 1.06885255]
 [0.06354782 0.26972857 0.07857296]
 [1.59102603 0.78588995 1.27142673]]

A @ B =
 [[0.96698434 0.31162843 0.64036909]
 [0.11369369 0.03608921 0.04795669]
 [0.96245587 0.31256866 0.75818804]]

A^T =
 [[0.4937956  0.02541913 0.63641041]
 [0.52273283 0.10789143 0.31435598]
 [0.42754102 0.03142919 0.50857069]]

Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Inverse of A:
 [[-1738.49317142  5079.27350915  1147.6078366 ]
 [ -273.36597559   809.98444464   179.75478663]
 [ 2344.47128859 -6856.71836426 -1545.2258284

In [170]:
import numpy as np

# --- 1. Генерація матриць ---
A = get_matrix(3, 3)
B = get_matrix(3, 3)
print("Матриця A:\n", A)
print("Матриця B:\n", B)

# --- 2. Додавання ---
C = add(A, B)
assert np.allclose(C, A + B), "Помилка в add"
print("\nA + B:\n", C)

# --- 3. Множення на скаляр ---
scalar = 2.5
D = scalar_multiplication(A, scalar)
assert np.allclose(D, A * scalar), "Помилка в scalar_multiplication"
print("\nA * scalar:\n", D)

# --- 4. Добуток матриць ---
E = dot_product(A, B)
assert np.allclose(E, A @ B), "Помилка в dot_product"
print("\nA @ B:\n", E)

# --- 5. Транспонування ---
At = matrix_transpose(A)
assert np.allclose(At, A.T), "Помилка в matrix_transpose"
print("\nA^T:\n", At)

# --- 6. Ідентична матриця ---
I = identity_matrix(3)
assert np.allclose(I, np.eye(3)), "Помилка в identity_matrix"
print("\nIdentity matrix:\n", I)

# --- 7. Інверсія матриці ---
# Перевіримо лише якщо матриця невироджена
try:
    A_inv = matrix_inverse(A)
    assert np.allclose(dot_product(A, A_inv), I), "Помилка в matrix_inverse"
    print("\nInverse of A:\n", A_inv)
except np.linalg.LinAlgError:
    print("\nМатриця A вироджена, інверсія неможлива")

# --- 8. Hadamard product ---
H = hadamard_product(A, B)
assert np.allclose(H, A * B), "Помилка в hadamard_product"
print("\nHadamard product A * B:\n", H)

# --- 9. Базис ---
basis_indices = basis(A)
print("\nІндекси базисних стовпців A:", basis_indices)

# --- 10. Норми ---
print("\nFrobenius norm of A:", norm(A, 'fro'))
print("Spectral norm of A:", norm(A, 2))
print("Infinity norm of A:", norm(A, np.inf))
print("1-norm of A:", norm(A, 1))

print("\n✅ Усі перевірки виконані!")


Матриця A:
 [[0.80367208 0.18657006 0.892559  ]
 [0.53934224 0.80744016 0.8960913 ]
 [0.31800347 0.11005192 0.22793516]]
Матриця B:
 [[0.42710779 0.81801477 0.86073058]
 [0.00695213 0.5107473  0.417411  ]
 [0.22210781 0.11986537 0.33761517]]

A + B:
 [[1.23077987 1.00458482 1.75328958]
 [0.54629437 1.31818746 1.3135023 ]
 [0.54011129 0.22991729 0.56555033]]

A * scalar:
 [[2.00918019 0.46642515 2.2313975 ]
 [1.3483556  2.01860039 2.24022825]
 [0.79500869 0.27512981 0.56983791]]

A @ B:
 [[0.54279599 0.85969269 1.07096299]
 [0.43499958 0.96099811 1.10379679]
 [0.18721304 0.34366179 0.39660657]]

A^T:
 [[0.80367208 0.53934224 0.31800347]
 [0.18657006 0.80744016 0.11005192]
 [0.892559   0.8960913  0.22793516]]

Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Inverse of A:
 [[-1.10488142 -0.72042503  7.15878341]
 [-2.09556234  1.30178602  3.08813214]
 [ 2.55325591  0.37657027 -7.09137136]]

Hadamard product A * B:
 [[0.3432546  0.15261706 0.76825283]
 [0.00374958 0.41239788 0.37403

In [171]:
import numpy as np

np.random.seed(42)  # для відтворюваності

def test_matrix_functions(num_tests=5, size=(3,3)):
    for i in range(num_tests):
        print(f"\n--- Тест {i+1} ---")
        n, m = size
        A = get_matrix(n, m)
        B = get_matrix(n, m)
        scalar = np.random.rand() * 10

        # 1. Додавання
        C = add(A, B)
        assert np.allclose(C, A + B), "add помилка"

        # 2. Множення на скаляр
        D = scalar_multiplication(A, scalar)
        assert np.allclose(D, A * scalar), "scalar_multiplication помилка"

        # 3. Добуток матриць
        if n == m:  # dot product тільки для квадратних матриць
            E = dot_product(A, B)
            assert np.allclose(E, A @ B), "dot_product помилка"

        # 4. Транспонування
        At = matrix_transpose(A)
        assert np.allclose(At, A.T), "matrix_transpose помилка"

        # 5. Ідентична матриця
        I = identity_matrix(n)
        assert np.allclose(I, np.eye(n)), "identity_matrix помилка"

        # 6. Інверсія (тільки якщо матриця невироджена)
        try:
            A_inv = matrix_inverse(A)
            assert np.allclose(dot_product(A, A_inv), I), "matrix_inverse помилка"
        except np.linalg.LinAlgError:
            print("Матриця вироджена, інверсія пропущена")

        # 7. Hadamard product
        H = hadamard_product(A, B)
        assert np.allclose(H, A * B), "hadamard_product помилка"

        # 8. Базис
        basis_indices = basis(A)
        assert all(0 <= idx < m for idx in basis_indices), "basis помилка"

        # 9. Норми
        fro = norm(A, 'fro')
        spectral = norm(A, 2)
        inf_norm = norm(A, np.inf)
        one_norm = norm(A, 1)
        assert fro >= 0 and spectral >= 0 and inf_norm >= 0 and one_norm >= 0, "norm помилка"

        print(f"✅ Тест {i+1} пройдено успішно!")

# Запускаємо перевірку
test_matrix_functions(num_tests=5, size=(3,3))



--- Тест 1 ---
✅ Тест 1 пройдено успішно!

--- Тест 2 ---
✅ Тест 2 пройдено успішно!

--- Тест 3 ---
✅ Тест 3 пройдено успішно!

--- Тест 4 ---
✅ Тест 4 пройдено успішно!

--- Тест 5 ---
✅ Тест 5 пройдено успішно!
